# ===================================================================
# IDENTIFICAÇÃO DA APLICAÇÃO
# ===================================================================
spring.application.name=mada-core
server.port=8080

# Configurações de Conexão com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/mada_db
spring.datasource.username=mada_admin
spring.datasource.password=mada_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (Mapeamento Objeto-Relacional)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ===================================================================
# update: Garante que as tabelas sejam criadas ou atualizadas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Opcional (apenas para desenvolvimento): Imprime o SQL formatado no terminal 
# para que você possa ver o Hibernate criando as tabelas do LAPROSOLDA.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===================================================================
# CONFIGURAÇÕES DE SEGURANÇA (JWT)
# ===================================================================
# A chave deve ter pelo menos 256 bits (32 caracteres) para HS256
security.jwt.secret-key=InovaLayer3D-MADA-Core-SecretKey-2026-SuperSecure-256Bits
security.jwt.expiration-time=86400000