spring.application.name=mada-core
spring.datasource.url=jdbc:postgresql://localhost:5432/mada_db
spring.datasource.username=mada_admin
spring.datasource.password=mada_password_123
spring.jpa.hibernate.ddl-auto=update
